### ISSUE TITLE
1. As a researcher or project lead, Kona wants to run a GNSS-A inversion of transducer positions and two-way travel times, so that he can position an array of 3 seafloor transponders.

### ISSUE THREAD

**Issue by vanitech** [seafloor-geodesy/gnatss#10]
## Overview

This user story essentially asks for a streamlined way to perform GNSS-A inversion.

### Retrieval
- [x] #16
- [x] #17
- [x] #18

### Create SFG Control/Parameters file in YAML file format
The parameter file will be using YAML file format, this decision has been made since this format is human and         machine readable.
- [x] #19 
- [x] #20
- [x] #21

### Create Python package for `sfgsolvvm.F` that also integrate `proc_sfgsolve_center_WG.csh` ('**sfgpy**')
Develop core functions as Python from FORTRAN **Note: For subroutines/functions unable to be redeveloped to Python, we'll use f2py to wrap it**
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [ ] #31
- [ ] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41

### Develop plug-in hook system at the core of the Python package
- [ ] #42
- [ ] #43
- [ ] #44
- [ ] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49
- [x] #50

### Create API usage docs and examples as a series of ipython notebooks in Jupyterbook
  - [x] #51
  - [x] #52
  - [x] #53
  - [x] #54

**Comment by lsetiawan** [comment]
Closing issue.. Re-organizing
