### ISSUE TITLE
feat: Add function for computing transducer offset from the antenna like `rotposatt` program

### ISSUE THREAD

**Issue by lsetiawan** [seafloor-geodesy/gnatss#100]
## Overview

Currently the full observation dataframe created from the [`load_data`](https://github.com/uw-ssec/offshore-geodesy/blob/9ffb3616fabdae9313560c9d3e2d608284edc012/src/gnatss/main.py#L427) method doesn't have the `roll`,`pitch`,`head` information or `d_e`,`d_n`,`d_u`. It would be great to create a function to add this functionality like what @SquirrelKnight has done in his original code in `deCoder_orig.py`:

```python
from scipy.spatial.transform import Rotation as rot

...

rph_file = glob(day_dir+'/WG*/RPH_TWTT')[0]
    
rph_df = pd.read_csv(rph_file, header=None, names=['dts','r','p','h'], sep='\s+')
rph_df = rph_df.drop_duplicates('dts')
rph_df.reset_index(drop=True,inplace=True)

...

# Compute transducer offset from the antenna
r = rot.from_euler('xyz',df_all[['roll0','pitch0','head0']].values,degrees=True)
offset = r.as_matrix()@atd_offset
d_e0 = offset[:,1]
d_n0 = offset[:,0]
d_u0 = -offset[:,2]
r = rot.from_euler('xyz',df_all[['roll1','pitch1','head1']].values,degrees=True)
offset = r.as_matrix()@atd_offset
d_e1 = offset[:,1]
d_n1 = offset[:,0]
d_u1 = -offset[:,2]

df_all['d_e0'] = d_e0
df_all['d_n0'] = d_n0
df_all['d_u0'] = d_u0
df_all['d_e1'] = d_e1
df_all['d_n1'] = d_n1
df_all['d_u1'] = d_u1
```

## TODO
- [x] #129 
- [x] #118
- [x] #211  
- [x] #119
- [x] #120 
- [x] #121

**Comment by madhavmk** [comment]
All TODO subtasks have been completed.
Closing this Issue :smile:
