### ISSUE TITLE
2. As a graduate student, Joe wants to retrieve solution accuracy metrics, so that he can exclude erroneous data.

### ISSUE THREAD

**Issue by vanitech** [seafloor-geodesy/gnatss#12]
- [ ] Set distance threshold to 150 and outlier threshold to >5000 as inputs to `gnatss`. (2)
- [ ] Add functionality to output or append deletions file in CSV format for data points outside the threshold (distance & outlier) after a run (34)
       - The decision to create a CSV format deletions file is because CSV format is both human and machine readable and easily parse-able with existing packages
- [x] #148
- [x] #141 
- [ ] Add functionality for `gnatss` to export QA/QC metrics log for each run that doesn't converge
  - Determine metrics to be exported (discussions are needed with researcher(s) for this) (13)
  - Create data structure for metrics (8)
  - Create function for exporting metrics as parse-able YAML file format (8)
  - Develop function or re-use from current Fortran for computing metrics (21)
  - Create test for metrics export function (8)
  - Create test for metrics computation function (8)
- [ ] Add functionality to process user defined flag file in CSV format
  - Create CSV reader function with pandas library(3)
  - Create csv headers validations with expected headers, removing the rest (3)
  - Create data types validation (8)
  - Create data values checks (8)
  - Create function to load in data (3)
  - Create function to connect to inversion computation (8)
- [ ] Add unit test for each functions that handles user flags to ensure accuracy (34)
- [ ] Add unit test for plotting (34)
- [ ] Create API Usage docs on the QA/QC validation process and options
  - Create ipython notebooks examples (13)
  - Test ipython notebook examples (8)
  - Setup autodoc to get docstrings and make sure it renders (8)

**Comment by lsetiawan** [comment]
Closing issue... Re-organizing
