### ISSUE TITLE
5. As a lab scientist, Alice wants to be able to rotate antenna positions using instantaneous roll, pitch, heading values and the body frame offsets, so that Alice can calculate transducer positions.

### ISSUE THREAD

**Issue by vanitech** [seafloor-geodesy/gnatss#13]

**Comment by lsetiawan** [comment]
Work for this user story are tracked in the following:

**Rotation** part is tracked in #100
**Kalman Filter** part is tracked in #187 

@SquirrelKnight has started this work in PR https://github.com/uw-ssec/offshore-geodesy/pull/167

**Comment by lsetiawan** [comment]
Closing issue ... Re-organizing
